export const SILENT_RFQ_ABI = [
  {
    inputs: [
      { internalType: "address", name: "buyer_", type: "address" },
      { internalType: "string", name: "description_", type: "string" },
      { internalType: "uint256", name: "deadline_", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyBid", type: "error" },
  { inputs: [], name: "AlreadyFinalized", type: "error" },
  { inputs: [], name: "DeadlineNotPassed", type: "error" },
  { inputs: [], name: "DeadlinePassed", type: "error" },
  { inputs: [], name: "InvalidBuyer", type: "error" },
  { inputs: [], name: "InvalidDeadline", type: "error" },
  { inputs: [], name: "InvalidDecryptionHandles", type: "error" },
  { inputs: [], name: "InvalidKMSSignatures", type: "error" },
  { inputs: [], name: "InvalidWinnerIndex", type: "error" },
  { inputs: [], name: "NoBids", type: "error" },
  { inputs: [], name: "NotBuyer", type: "error" },
  { inputs: [], name: "NotFinalized", type: "error" },
  {
    inputs: [
      { internalType: "bytes32", name: "handle", type: "bytes32" },
      { internalType: "address", name: "sender", type: "address" },
    ],
    name: "SenderNotAllowedToUseHandle",
    type: "error",
  },
  { inputs: [], name: "TooManyVendors", type: "error" },
  { inputs: [], name: "WinnerAlreadyRevealed", type: "error" },
  { inputs: [], name: "WinnerNotRevealed", type: "error" },
  { inputs: [], name: "ZamaProtocolUnsupported", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "vendor", type: "address" },
      { indexed: false, internalType: "uint256", name: "vendorIndex", type: "uint256" },
    ],
    name: "BidSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes32[]", name: "handlesList", type: "bytes32[]" },
      { indexed: false, internalType: "bytes", name: "abiEncodedCleartexts", type: "bytes" },
    ],
    name: "PublicDecryptionVerified",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "buyer", type: "address" },
      { indexed: false, internalType: "string", name: "description", type: "string" },
      { indexed: false, internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "RFQCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "buyer", type: "address" }],
    name: "RFQFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "winnerIndex", type: "uint256" },
      { indexed: false, internalType: "address", name: "winner", type: "address" },
    ],
    name: "WinnerRevealed",
    type: "event",
  },
  {
    inputs: [],
    name: "buyer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "handlesList", type: "bytes32[]" },
      { internalType: "bytes", name: "abiEncodedCleartexts", type: "bytes" },
      { internalType: "bytes", name: "decryptionProof", type: "bytes" },
    ],
    name: "callbackRevealWinner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "confidentialProtocolId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deadline",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "description",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "finalize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "finalized",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBestBid",
    outputs: [{ internalType: "euint64", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBestVendorIndex",
    outputs: [{ internalType: "euint64", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getVendors",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "hasBid",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "revealedWinnerIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "externalEuint64", name: "inputBid", type: "bytes32" },
      { internalType: "bytes", name: "inputProof", type: "bytes" },
    ],
    name: "submitBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "vendorCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "vendors",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "winnerAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "winnerRevealed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
